"""Initial migration

Revision ID: 4d2379e619df
Revises: 
Create Date: 2026-04-26 00:46:43.154592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d2379e619df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_audit_logs_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_event', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_name'), 'audit_logs', ['event_name'], unique=False)
    op.drop_index('idx_bills_academic_year', table_name='bills')
    op.drop_index('idx_bills_status', table_name='bills')
    op.drop_index('idx_bills_user_id', table_name='bills')
    op.create_index(op.f('ix_bills_academic_year'), 'bills', ['academic_year'], unique=False)
    op.create_index(op.f('ix_bills_status'), 'bills', ['status'], unique=False)
    op.create_index(op.f('ix_bills_user_id'), 'bills', ['user_id'], unique=False)
    op.drop_index('idx_payments_bill_id', table_name='payments')
    op.drop_index('idx_payments_user_id', table_name='payments')
    op.create_index(op.f('ix_payments_bill_id'), 'payments', ['bill_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.drop_index('idx_receipts_user_id', table_name='receipts')
    op.create_index(op.f('ix_receipts_user_id'), 'receipts', ['user_id'], unique=False)
    op.drop_index('idx_refunds_user_id', table_name='refunds')
    op.create_index(op.f('ix_refunds_user_id'), 'refunds', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_user_id'), table_name='refunds')
    op.create_index('idx_refunds_user_id', 'refunds', ['user_id'], unique=False)
    op.drop_index(op.f('ix_receipts_user_id'), table_name='receipts')
    op.create_index('idx_receipts_user_id', 'receipts', ['user_id'], unique=False)
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_bill_id'), table_name='payments')
    op.create_index('idx_payments_user_id', 'payments', ['user_id'], unique=False)
    op.create_index('idx_payments_bill_id', 'payments', ['bill_id'], unique=False)
    op.drop_index(op.f('ix_bills_user_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_status'), table_name='bills')
    op.drop_index(op.f('ix_bills_academic_year'), table_name='bills')
    op.create_index('idx_bills_user_id', 'bills', ['user_id'], unique=False)
    op.create_index('idx_bills_status', 'bills', ['status'], unique=False)
    op.create_index('idx_bills_academic_year', 'bills', ['academic_year'], unique=False)
    op.drop_index(op.f('ix_audit_logs_event_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.create_index('idx_audit_logs_event', 'audit_logs', ['event_name'], unique=False)
    op.create_index('idx_audit_logs_created', 'audit_logs', ['created_at'], unique=False)
    op.alter_column('audit_logs', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
